### ISSUE TITLE
Support for arbitrary keywords and categories for dealer profiles

### ISSUE THREAD

**Issue by Fenrikur** [eurofurence/ef-app_backend-dotnet-core#29]
https://github.com/eurofurence/dealer-registration/issues/38 migrated the Dealers' Den registration system from using a static, predefined set of categories to an arbitrary list of categorised keywords.

* define format in which this data should be provided to the app backend
* ingest data and provide altered model to apps via API

**Comment by Metawolve** [comment]
Solved with #112
